### ISSUE TITLE
Setup repository

### ISSUE THREAD

**Issue by tzdybal** [rollkit/celestia-openrpc#1]
```[tasklist]
### Tasks
- [x] Add `NOTICE`
- [x] Update README.md
- [x] Setup branch protection
- [x] Setup codeowners
- [x] Setup housekeeping actions
- [x] Setup dependabot
```
